language: haskell

dist: xenial

addons:
  apt:
    packages:
      - cabal-install-2.2

ghc:
  - "8.6.3"
  - "8.4.4"
  - "8.2.2"
  - "8.0.2"
  - "7.10.3"

install:
  - /opt/cabal/bin/cabal-2.2 new-configure

script:
  - /opt/cabal/bin/cabal-2.2 new-build
  - /opt/cabal/bin/cabal-2.2 new-haddock
